version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./demo
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./demo:/app
      - /app/node_modules # Don't overwrite node_modules with host version
    depends_on:
      - backend
